version: 0.2

env:
  variables:
    S3_BUCKET: "langames.online"
    CLOUDFRONT_DISTRIBUTION_ID: "YOUR_DISTRIBUTION_ID" # optional

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase complete"

  pre_build:
    commands:
      - echo "Pre-build phase"
      - ls -la

  build:
    commands:
      - echo "No build step required for static HTML site"

  post_build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync . s3://$S3_BUCKET \
          --delete \
          --exclude ".git/*" \
          --exclude "buildspec.yml"

      - |
        if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "Invalidating CloudFront cache"
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DISTRIBUTION_ID \
            --paths "/*"
        fi

artifacts:
  files:
    - '**/*'
